---
mail_domain: mydomain.com # the 'mail' subdomain will be added throughout the playbook - don't add it here.
mail_user: hello # the main e-mail account. Postmaster will be aliased to this account
mail_aliases: # optionally add more aliases to main account
  - admin
  - postmaster
mail_password: changeme # use ansible vault for extra security
mail_quota: 20000 # amount of available disk space in MB for the main e-mail account
mail_storage: /var/mail # this will be the vmail home and where all emails will be stored
webserver: false
secretpath: '{{ inventory_dir | realpath + "/secret" }}'