---
mail_domain: mydomain.tld # the 'mail' subdomain will be added throughout the playbook - don't add it here.
mail_user: mymainuser # the main e-mail account. Postmaster will be aliased to this account
mail_email_address: '{{ mail_user }}@{{ mail_domain }}'
mail_password: <run 'ansible-vault encrypt_string' and paste the contents here>
mail_storage: /var/vmail # this will be the vmail home and where all emails will be stored

secretpath: '{{ inventory_dir | realpath + "/secret" }}'
