---
- name: Install SQL packages
  apt: pkg={{ item }} state=installed
  with_items:
    - mariadb-server
    - python3-pymysql
    - dovecot-core

- name: Install PyMySQL with pip3
  command: pip3 install PyMySQL

- name: Set MariaDB root user password
  command: mysql --execute="SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{root_db_password}}');"
  no_log: True

- name: Create  MariaDB .my.cnf
  template:
    src: "my.cnf.jinja2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  no_log: True

- name: Generate SHA-512 hash of password
  command: doveadm pw -s SHA512-CRYPT -p "{{ mail_password }}"
  no_log: True
  register: mail_password_sha512

- name: Copy SQL commands to run in new database
  template:
    src: vmail.sql.jinja2
    dest: /tmp/vmail.sql
  no_log: True

- name: check if vmail DB exists
  shell: mysql -e "SHOW DATABASES LIKE 'vmail'" -sN
  register: dbstatus

- name: Delete vmail database
  command: mysql -e "DROP DATABASE vmail" -sN
  ignore_errors: true
  when: recreate_databases | default('false')  == 'true'

- name: Create vmail database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: vmail 
    encoding: utf8
    target: /tmp/vmail.sql
    state: import
  when: (not dbstatus.stdout_lines) or (recreate_databases | default('false')  == 'true') 

- name: Cleanup SQL commands temp file
  file:
    path: /tmp/vmail.sql
    state: absent

- name: Create database user with password and define privileges
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    name: vmail
    password: "{{ vmail_db_password }}"
    priv: 'vmail.*:SELECT'
    state: present

- block:
  - name: Copy SQL commands to run in new database
    template:
      src: sogo.sql.jinja2
      dest: /tmp/sogo.sql
    no_log: True

  - name: check if sogo DB exists
    shell: mysql -e "SHOW DATABASES LIKE 'sogo'" -sN
    register: dbstatus

  - name: Delete sogo database
    command: mysql -e "DROP DATABASE sogo" -sN
    ignore_errors: true
    when: recreate_databases | default('false')  == 'true'

  - name: Create sogo database
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: sogo 
      encoding: utf8
      target: /tmp/sogo.sql
      state: import
    when: (not dbstatus.stdout_lines) or (recreate_databases | default('false')  == 'true') 

  - name: Cleanup SQL commands temp file
    file:
      path: /tmp/sogo.sql
      state: absent

  - name: Create sogo database user with password and define privileges
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: "%"
      name: sogo
      password: "{{ sogo_db_password }}"
      priv: 'sogo.*:ALL'
      state: present
  
  - name: Modify sogo database user to access vmail accounts
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: "%"
      name: sogo
      append_privs: yes
      priv: 'vmail.accounts:SELECT'
      state: present
  when: sogo | default('true')  == 'true'