---
- name: Install DNS packages
  apt: pkg={{ item }} state=installed
  with_items:
    - unbound
    - resolvconf
    - dnsutils

- name: Update DNSSEC Root key
  command: unbound-anchor -a /var/lib/unbound/root.key
  become_user: unbound

- name: Reload DNS service
  service:
    name: unbound
    state: reloaded

- name: Add own DNS server to resolv
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: "nameserver 127.0.0.1"
    state: present
