---
- name: Install DNS packages
  apt:
    state: present
    pkg:
    - unbound
    - resolvconf
    - dnsutils
    - unbound-anchor

- name: Update DNSSEC Root key
  command: unbound-anchor -a /var/lib/unbound/root.key

- name: Set correct ownership to DNSSEC Root key 
  file:
    path: /var/lib/unbound/root.key
    state: touch
    owner: unbound
    group: unbound

- name: Restart DNS service
  service:
    name: unbound
    state: restarted

- name: Add own DNS server to resolv
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    line: "nameserver 127.0.0.1"
    state: present
    create: true