---

- name: Deploy essential tools and packages
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: mailserver/bootstrap
      when: bootstrap | default('true') | bool
    - role: mailserver/dns
      when: dns | default('true') | bool
    - role: mailserver/certbot
      when: certbot | default('true') | bool
    - role: mailserver/sql
      when: sql | default('true') | bool
    - role: mailserver/postfix
      when: postfix | default('true') | bool
    - role: mailserver/dovecot
      when: dovecot | default('true') | bool
    - role: mailserver/rspamd
      when: rspamd | default('true') | bool
    - role: mailserver/sogo
      when: sogo | default('true') | bool
    - role: mailserver/nginx
      when: nginx | default('true') | bool

- name: Make sure all services are running
  hosts: all
  roles:
    - role: mailserver/restartenable
  tags: always