---

- name: Deploy essential tools and packages
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: mailserver/bootstrap
      when: bootstrap | default('true') | bool
    - role: mailserver/dns
      when: dns | default('true') | bool
    - role: mailserver/certbot
      when: certbot | default('true') | bool
    - role: mailserver/sql
      when: sql | default('true') | bool
    - role: mailserver/sql
      when: sql | default('true') | bool
#  tags: clusterbuild_clean