---
- name: Add Sogo/Axis repository key
  when: ansible_distribution == 'Ubuntu'
  apt:
    deb: http://www.axis.cz/linux/debian/axis-archive-keyring.deb

- name: Add Sogo/Axis repository
  when: ansible_distribution == 'Ubuntu'
  lineinfile:
    path: /etc/apt/sources.list.d/sogo-axis.list
    line: "deb http://www.axis.cz/linux/debian {{ ansible_distribution_release }} sogo-v5"
    create: yes

- name: Update apt cache
  when: ansible_distribution == 'Ubuntu'
  apt: update_cache=yes

- name: Install Sogo packages
  apt:
    state: present
    pkg:
    - sogo

- name: Stop sogo services
  service:
    name: "{{ item }}"
    state: stopped
  loop:
    - sogo
    - memcached

- name: Copy sogo configuration
  template:
    src: sogo.conf.jinja2
    dest: /etc/sogo/sogo.conf
  no_log: True

- name: Sogo increase WOWorkersCount from default of 3
  lineinfile:
    dest: /etc/default/sogo
    line: "PREFORK=8"
    state: present

- name: Restart sogo services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - sogo
    - memcached