---
- name: Install nginx packages
  apt:
    state: present
    pkg:
    - nginx

- shell: /bin/rm -rf /etc/nginx/sites-enabled/*
- shell: /bin/rm -rf /etc/nginx/sites-available/*

- name: Copy nginx server configuration
  template:
    src: "domain.jinja2"
    dest: "/etc/nginx/sites-available/mail.{{ mail_domain }}"

- name: Create symbolic link 
  file:
    src: "/etc/nginx/sites-available/mail.{{ mail_domain }}"
    dest: "/etc/nginx/sites-enabled/mail.{{ mail_domain }}"
    state: link

- name: Configure safe SSL ciphers for nginx
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    insertafter: 'ssl_prefer_server_ciphers'
    line: "        ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5:!kDHE;"


- name: Extract base website into /var/www/html
  unarchive:
    src: website.tar
    dest: /var/www/html

- name: Reload nginx configuration
  command: nginx -s reload