---
- name: Install Dovecot packages
  apt: pkg={{ item }} state=installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd
    - dovecot-mysql
    - dovecot-sieve
    - dovecot-managesieved

- name: Stop Dovecot service
  service:
    name: dovecot
    state: stopped

- name: Create email storage directory
  file:
    path: "{{ mail_storage }}/vhosts/{{ mail_domain }}"
    state: directory
    recurse: yes
    owner: vmail
    group: vmail

- name: Copy Dovecot main configurations
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/dovecot/{{ item }}"
  loop:
    - dovecot.conf
    - dovecot-sql.conf.ext

- name: Copy Dovecot configuration files
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  loop:
    - 10-mail.conf
    - 10-auth.conf
    - 10-master.conf
    - 10-ssl.conf
    - auth-sql.conf.ext


- name: Copy all sieve configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ mail_storage }}/sieve/global/{{ item }}"
  loop:
    - spam-global.sieve
    - learn-spam.sieve
    - learn-ham.sieve

- name: Make sure dovecot configuration files have the correct permissions
  file:
    path: /etc/dovecot
    state: directory
    mode: '640'
    recurse: yes
    owner: vmail
    group: dovecot

- name: Start Dovecot service
  service:
    name: dovecot
    state: started
