---
- name: Install Dovecot packages
  apt:
    state: present
    pkg:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd
    - dovecot-mysql
    - dovecot-sieve
    - dovecot-managesieved

- name: Stop Dovecot service
  service:
    name: dovecot
    state: stopped

- name: Create email storage directory
  file:
    path: "{{ mail_storage }}/vhosts/{{ mail_domain }}"
    state: directory
    recurse: yes
    owner: vmail
    group: vmail

- name: Copy Dovecot main configurations
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/dovecot/{{ item }}"
  loop:
    - dovecot.conf
    - dovecot-sql.conf.ext

- name: Copy Dovecot configuration files
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
  loop:
    - 10-mail.conf
    - 10-auth.conf
    - 10-master.conf
    - 10-ssl.conf
    - 15-lda.conf
    - 20-lmtp.conf
    - auth-sql.conf.ext

- name: Copy all sieve configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ mail_storage }}/sieve/global/{{ item }}"
  loop:
    - spam-global.sieve
    - learn-spam.sieve
    - learn-ham.sieve

- name: Compile sieve filters
  command: /usr/bin/sievec .
  args:
    chdir: "{{ mail_storage }}/sieve/global/"

- name: Create custom sieve filters folder
  file:
    path: "{{ mail_storage }}/sieve/{{ mail_domain }}/{{ mail_user }}"
    state: directory
    recurse: yes
    owner: vmail
    group: dovecot

- name: Make sure dovecot configuration files have the correct permissions
  file:
    path: /etc/dovecot
    state: directory
    mode: '640'
    recurse: yes
    owner: vmail
    group: dovecot

- name: Disable default PAM authentication for Dovecot
  replace:
    path: "/etc/dovecot/conf.d/auth-system.conf.ext"
    regexp: '^passdb {(.*\n)*}$'
    replace: ''

- name: Start Dovecot service
  service:
    name: dovecot
    state: started
