---
- name: Install Dovecot packages
  apt: pkg={{ item }} state=installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql
    - dovecot-sieve
    - dovecot-managesieved

- name: Stop Dovecot service
  service:
    name: dovecot
    state: stopped

- shell: /bin/rm -rf /etc/dovecot/*

- name: Copy Dovecot main configuration
  template:
    src: dovecot.conf.jinja2
    dest: /etc/dovecot/dovecot.conf

- name: Copy Dovecot SQL configuration
  template:
    src: dovecot-sql.conf.jinja2
    dest: /etc/dovecot/dovecot-sql.conf
    mode: '440'

- name: Copy all sieve configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ mail_storage }}/sieve/global/{{ item }}"
  loop:
    - spam-global.sieve
    - learn-spam.sieve
    - learn-ham.sieve

