---
- name: Install Postfix packages
  apt: pkg={{ item }} state=installed
  with_items:
    - postfix
    - postfix-mysql
  
- name: Stop Postfix service
  service:
    name: postfix
    state: stopped

- name: Remove default configuration
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/postfix/sasl
    - /etc/postfix/master.cf
    - /etc/postfix/main.cf.proto
    - /etc/postfix/master.cf.proto
  
- name: Copy Postfix main configuration
  template:
    src: main.cf.jinja2
    dest: /etc/postfix/main.cf
    mode: '440'

- name: Copy Postfix master configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/postfix/{{ item }}"
  loop:
    - master.cf
    - submission_header_cleanup

- name: Create Postfix SQL configuration directory
  file:
    path: /etc/postfix/sql
    state: directory
    mode: '640'
    recurse: yes

- name: Copy Postfix SQL configuration
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/postfix/sql/{{ item }}"
    mode: '640'
  loop:
    - accounts.cf
    - aliases.cf
    - domains.cf
    - recipient-access.cf
    - sender-login-maps.cf
    - tls-policy.cf

- name: Create extra empty configuration files for Postfix
  file:
    path: "/etc/postfix/{{ item }}"
    state: touch
    mode: '640'
  loop:
    - without_ptr
    - postscreen_access

- name: Map all PTR exceptions
  command: postmap /etc/postfix/without_ptr

- name: Check for new aliases
  command: newaliases

- name: Reload Postfix service
  service:
    name: postfix
    state: reloaded