---
- name: Install Postfix packages
  apt:
    state: present
    pkg:
    - postfix
  
- name: Stop Postfix service
  service:
    name: postfix
    state: stopped

- name: Copy Postfix configuration
  template:
    src: "{{ item }}.jinja2"
    dest: "/etc/postfix/{{ item }}"
#    mode: '640'
  loop:
    - main.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-email2email.cf

- name: Copy Postfix master configuration
  copy:
    src: master.cf
    dest: /etc/postfix/master.cf

- name: Make sure postfix configuration files have the correct permissions
  file:
    path: /etc/postfix
    state: directory
    mode: '640'
    recurse: yes

- name: Install Postfix packages
  apt:
    state: present
    pkg:
    - postfix-mysql
    - postfix-policyd-spf-python

- name: Copy the spf validation config file
  copy:
    src: policyd-spf.conf
    dest: /etc/postfix-policyd-spf-python/policyd-spf.conf   

- name: Reload Postfix service
  service:
    name: postfix
    state: reloaded

- name: Start Postfix service
  service:
    name: postfix
    state: started

- name: Test domain can be resolved by postfix
  command: postmap -q {{ mail_domain }} mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
  register: result
  failed_when:
    - '"1" not in result.stdout'

- name: Test main email can be resolved by postfix
  command: postmap -q {{ mail_user }}@{{ mail_domain }} mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
  register: result
  failed_when:
    - '"1" not in result.stdout'

- name: Test postmaster can be resolved by postfix
  command: postmap -q postmaster@{{ mail_domain }} mysql:/etc/postfix/mysql-virtual-alias-maps.cf
  register: result
  failed_when:
    - '"{{ mail_user }}@{{ mail_domain }}" not in result.stdout'
